x-faucon-sim-base: &faucon-sim-base
  image: ghcr.io/ngnepist/faucon_ws/faucon_simulator
  network_mode: host
  environment:
    - DISPLAY=${DISPLAY:-}
    - QT_X11_NO_MITSHM=1
    - GZ_SIM_RESOURCE_PATH=/Faucon_ma64/install/faucon_description/share:/Faucon_ma64/install/faucon_description/share/faucon_description:${GZ_SIM_RESOURCE_PATH:-}
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - ./data:/Faucon_ma64/data
  devices:
    - /dev/dri:/dev/dri
  stdin_open: true
  tty: true
  extends:
    file: ./docker/docker-compose.yml
    service: common

services:  
# -----------------------------------------------------------------------------
#                                   Simulateurs
# -----------------------------------------------------------------------------
  build-image-simulator:
    image: ghcr.io/ngnepist/faucon_ws/faucon_simulator
    build:
      context: .
      dockerfile: ./docker/simulator.dockerfile

  faucon-rviz:
    <<: *faucon-sim-base
    command: bash -c "rviz2 -d /Faucon_ma64/install/faucon_config/share/faucon_config/config/viz/faucon_sim.rviz --ros-args -p use_sim_time:=true"
    container_name: faucon_rviz_sim
    depends_on:
      faucon-ihm:
        condition: service_started

  faucon-gazebo:
    <<: *faucon-sim-base
    command: bash -c "ros2 launch faucon_bringup sim.launch.py"
    container_name: faucon_gazebo_sim
    depends_on:
      faucon-rviz:
        condition: service_started

  faucon-ihm:
    <<: *faucon-sim-base
    command: bash -c "ros2 launch faucon_bringup ihm.launch.py use_sim_time:=true"
    container_name: faucon_ihm_sim


  faucon-teleop:
    <<: *faucon-sim-base
    command: bash -c "ros2 run pynput_teleop default.bash"
    container_name: faucon_teleop_sim

  faucon-loc-sim:
    <<: *faucon-sim-base
    command: bash -c "sleep 5 && ros2 launch faucon_bringup loc.launch.py use_sim_time:=true"
    container_name: faucon_loc_sim
    depends_on:
      faucon-gazebo:
        condition: service_started

  faucon-nav-sim:
    <<: *faucon-sim-base
    command: bash -c "sleep 10 && ros2 launch faucon_bringup nav.launch.py"
    container_name: faucon_nav_sim
    cap_add:
    - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    depends_on:
      faucon-loc-sim:
        condition: service_started