services:
  common:
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    ipc: host
    network_mode: host
    volumes:
      - ../src/common/faucon/faucon_config/config:/faucon_ws/install/faucon_config/share/faucon_config/config/
      - ../src/common/faucon/faucon_bringup/launch:/faucon_ws/install/faucon_bringup/share/faucon_bringup/launch/
